In [6]:
import numpy as np

In [7]:
# Creating Numpy Array
a = np.array([23,24,23,42])
print(a)

[23 24 23 42]


In [8]:
x = [34,54,24,53,43,33,42]
a = np.array(x)
print(a)
print(type(a)) # for checking type

[34 54 24 53 43 33 42]
<class 'numpy.ndarray'>


In [9]:
l = []
for i in range(1,6):
    int_1 = int(input("Enter = "))
    l.append(int_1)
print(np.array(l))

Enter = 


ValueError: invalid literal for int() with base 10: ''

In [12]:
# 1-D Array.....

a = np.array([23,24,45,63,53])
print(a)
print(a.ndim)

[23 24 45 63 53]
1


In [13]:
# 2-D Array....
a = np.array([[23,34],[54,64],[34,34]])
print(a)
print(a.ndim)

[[23 34]
 [54 64]
 [34 34]]
2


In [21]:
# 3-D Array
ar3 = np.array([[[32,34,55],[34,53,65]],[[23,24,34],[34,34,54]],[[34,34,23],[34,76,85]]])
print(ar3)
print(ar3.ndim)

[[[32 34 55]
  [34 53 65]]

 [[23 24 34]
  [34 34 54]]

 [[34 34 23]
  [34 76 85]]]
3


In [23]:
# n-D Array......
arn = np.array([23,43,43,55,74,56,75,56,43,34],ndmin= 6)
print(arn)
print(arn.ndim)

[[[[[[23 43 43 55 74 56 75 56 43 34]]]]]]
6


# Create numpy array using Numpy Function.....


In [27]:
# Creating array that contain zeros...

ar_zero = np.zeros(4)
print(ar_zero)
print("-----------------------------------")
ar_zero1 = np.zeros((3,4))
print(ar_zero1)




[0. 0. 0. 0.]
-----------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
# Creating array that contains Ones......
ar_one = np.ones(4)
print(ar_one)
print("--------------------------------------")
ar_one1 = np.ones((3,4))
print(ar_one1)

[1. 1. 1. 1.]
--------------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:
a = np.arange(2,8)
print(a)

[2 3 4 5 6 7]


In [31]:
# Create an array that contain diagonal ones....
a = np.eye(6,6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [34]:
# Linspace.....
a = np.linspace(0,20 , num = 5)
print(a)

[ 0.  5. 10. 15. 20.]


# Random Functions...

In [35]:
# rand()... Its generates a random value b/w 0 to 1....
r = np.random.rand(5)
print(r)

[0.95675746 0.95878971 0.5451555  0.92862614 0.32224458]


In [36]:
# randn().... Its generatas a random value close to zero(Positive/Negative)...
r1 = np.random.randn(5)
print(r1)

[-0.53936677 -0.67079411 -0.90283785 -0.13607981 -0.25702551]


In [41]:
# randf().... It returns an array if specified shape and fills it with random float in the half open interval(0.0, 1.0).
r2 = np.random.ranf(5)
print(r2)

[0.61030444 0.08458108 0.31884255 0.78400437 0.57964019]


In [43]:
# randint().... It generates a random number from given range...
r3 = np.random.randint(0,10,5)
print(r3)

[9 6 7 7 7]


# Data Types....

In [44]:
# Check data type of array....
ar = np.array([23,43,55,45])
print(ar)
print(ar.dtype)

[23 43 55 45]
int32


In [46]:
# Change data type of array....
ar_1 = np.array([23,43,55,45], dtype = "f")
print(ar_1)
print(ar.dtype)

[23. 43. 55. 45.]
float32


In [50]:
# Check data type of array....
ar = np.array([23,43,55,45])
new_1 = ar.astype(str)
print(ar)
print(ar.dtype)

print(new_1)
print(new_1.dtype)

[23 43 55 45]
int32
['23' '43' '55' '45']
<U11


# Arithmetic Operations In Numpy Array..

In [51]:
ar = np.array([23,43,55,45])
ar1 = ar+2
print(ar1)

[25 45 57 47]


In [53]:
ar = np.array([23,43,55,45])
ar1 = np.array([34,34,65,76])
s = ar+ar1
print(s)


[ 57  77 120 121]


In [58]:
ar = np.array([23,43,55,45])
ar1 = np.array([34,34,65,76])
s = np.add(ar,ar1)
print(s)

[ 57  77 120 121]


In [54]:
ar = np.array([23,43,55,45])
ar1 = ar-2
print(ar1)

[21 41 53 43]


In [61]:
ar = np.array([23,43,55,45])
ar1 = np.array([34,34,65,76])
s = np.subtract(ar,ar1)
print(s)

[-11   9 -10 -31]


In [55]:
ar = np.array([23,43,55,45])
ar1 = ar*2
print(ar1)

[ 46  86 110  90]


In [62]:
ar = np.array([23,43,55,45])
ar1 = np.array([34,34,65,76])
s = np.multiply(ar,ar1)
print(s)

[ 782 1462 3575 3420]


In [56]:
ar = np.array([23,43,55,45])
ar1 = ar/2
print(ar1)

[11.5 21.5 27.5 22.5]


In [63]:
ar = np.array([23,43,55,45])
ar1 = np.array([34,34,65,76])
s = np.divide(ar,ar1)
print(s)

[0.67647059 1.26470588 0.84615385 0.59210526]


In [57]:
ar = np.array([23,43,55,45])
ar1 = ar%2
print(ar1)

[1 1 1 1]


In [64]:
ar = np.array([23,43,55,45])
ar1 = np.array([34,34,65,76])
s = np.mod(ar,ar1)
print(s)

[23  9 55 45]


In [65]:
ar = np.array([23,43,55,45])
ar1 = np.array([34,34,65,76])
s = np.power(ar,ar1)
print(s)

[  845753105 -1563005767  1343374903  1061737009]


In [66]:
ar = np.array([23,43,55,45])
ar1 = np.array([34,34,65,76])
s = np.reciprocal(ar,ar1)
print(s)

[0 0 0 0]


In [68]:
# Arithmetic Operation for 2-D Array
ar = np.array([[23,43],[55,45],[23,64],[66,45]])
ar1 = np.array([[34,34],[65,76],[23,54],[75,56]])
s = np.add(ar,ar1)
print(s)

[[ 57  77]
 [120 121]
 [ 46 118]
 [141 101]]


# Arithmetic functions in Numpy Array....

# np.min(x)
# np.max(x)
# np.argmin(x)
# np.sqrt(x)
# np.sin(x)
# np.cos(x)
# np.cumsum(x)

In [70]:
ar = np.array([1,3,5,6,7,4])
print("Min : ",np.min(ar), np.argmin(ar))
print("Max : ",np.max(ar), np.argmax(ar))

Min :  1 0
Max :  7 4


In [74]:
ar = np.array([[1,3],[5,6],[7,4]])
print("Min : ", np.min(ar,axis = 0))
print("Min : ", np.min(ar,axis = 1))
print("Max : ", np.max(ar,axis = 0))
print("Max : ", np.max(ar,axis = 1))

Min :  [1 3]
Min :  [1 5 4]
Max :  [7 6]
Max :  [3 6 7]


In [75]:
ar = np.array([[1,3],[5,6],[7,4]])
print(np.sqrt(ar))

[[1.         1.73205081]
 [2.23606798 2.44948974]
 [2.64575131 2.        ]]


In [76]:
ar = np.array([[1,3],[5,6],[7,4]])
print(np.sin(ar))

[[ 0.84147098  0.14112001]
 [-0.95892427 -0.2794155 ]
 [ 0.6569866  -0.7568025 ]]


In [77]:
ar = np.array([[1,3],[5,6],[7,4]])
print(np.cos(ar))

[[ 0.54030231 -0.9899925 ]
 [ 0.28366219  0.96017029]
 [ 0.75390225 -0.65364362]]


# Shape And Reshaping in Numpy Array....